- name: Install Libvirt and KVM dependencies
  apt: 
    name: "{{ packages }}"
    update_cache: yes 
    state: present
    cache_valid_time: 3600
  vars:
    packages:
      - libvirt-daemon-system
      - libvirt-clients
      - qemu-kvm
      - python3-libvirt
      - bridge-utils
      - cpu-checker
      - virtinst

- name: Configure Libvirtd daemon
  lineinfile: dest=/etc/libvirt/libvirtd.conf regexp="{{ item.regexp }}" line="{{ item.line }}" insertafter=EOF 
  with_items: 
   - line: 'listen_tls = 0'
     regexp: '^#?listen_tls'
   - line: 'listen_tcp = 1'
     regexp: '^#?listen_tcp'
   - line: 'tcp_port = \"16509\"'
     regexp: '^#?tcp_port'
   - line: 'auth_tcp = \"none\"'
     regexp: '^#?auth_tcp'
   - line: 'mdns_adv = 0'
     regexp: '^#?mdns_adv'

- name: Configure libvirt socket settings
  lineinfile: dest=/etc/default/libvirtd regexp="{{ item.regexp }}" line="{{ item.line }}" create=yes
  with_items:
   - line: 'LIBVIRTD_ARGS="--listen"'
     regexp: '^LIBVIRTD_ARGS'

- name: Remove libvirtd AppArmor definition from the kernel
  shell: apparmor_parser -R /etc/apparmor.d/usr.sbin.libvirtd
  args:
    creates: /etc/apparmor.d/disable/usr.sbin.libvirtd
  ignore_errors: yes

- name: Remove virt-aa-helper AppArmor definition from the kernel
  shell: apparmor_parser -R /etc/apparmor.d/usr.lib.libvirt.virt-aa-helper
  args:
    creates: /etc/apparmor.d/disable/usr.lib.libvirt.virt-aa-helper
  ignore_errors: yes

- name: Disable AppArmor for libvirtd
  file: state=link src="/etc/apparmor.d/usr.sbin.libvirtd" path="/etc/apparmor.d/disable/usr.sbin.libvirtd"

- name: Disable AppArmor for virt-aa-helper
  file: state=link src="/etc/apparmor.d/usr.lib.libvirt.virt-aa-helper" path="/etc/apparmor.d/disable/usr.lib.libvirt.virt-aa-helper" force=yes

- name: Stop libvirtd service
  service: name=libvirtd state=stopped
  ignore_errors: yes

- name: Stop libvirtd socket
  service: name=libvirtd.socket state=stopped
  ignore_errors: yes

- name: Kill any remaining libvirtd processes
  shell: pkill -9 libvirtd || true
  ignore_errors: yes

- name: Kill any remaining dnsmasq processes started by libvirt
  shell: pkill -9 dnsmasq || true
  ignore_errors: yes

- name: Wait for processes to fully stop
  pause:
    seconds: 5

- name: Start virtlogd
  service: name=virtlogd state=started enabled=true

- name: Start libvirtd socket
  service: name=libvirtd.socket state=started enabled=true

- name: Start libvirtd service
  service: name=libvirtd state=started enabled=true
