---
- name: Install MySQL 8.0
  apt: 
    name: 
      - mysql-server
      - mysql-client
      - python3-mysqldb
    update_cache: yes 
    state: present 
    cache_valid_time: 3600

- name: Stop mysql-server
  service: name=mysql state=stopped

- name: Configure MySQL for CloudStack
  copy: src=cloudstack.cnf dest=/etc/mysql/conf.d/cloudstack.cnf

- name: Start mysql-server
  service: name=mysql state=started enabled=true

- name: Wait for MySQL to start
  wait_for: port=3306 timeout=30

- name: Check if mysql root password is enabled
  mysql_variables: 
    login_user: root 
    login_password: "{{ database_root_password }}"
    variable: timestamp
  register: chktime
  ignore_errors: True

- name: Define mysql root password
  mysql_user: 
    name: root 
    password: "{{ database_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  when: chktime.msg[0] == "u"

- name: Update root user plugin to mysql_native_password
  command: mysql --user=root --password="{{ database_root_password }}" -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ database_root_password }}';"
  when: chktime.msg[0] != "u"

- name: Create CloudStack database user
  mysql_user:
    name: cloud
    password: "{{ database_cloud_password }}"
    host: localhost
    priv: '*.*:ALL,GRANT'
    state: present
    login_user: root
    login_password: "{{ database_root_password }}"
