---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install common utilities
  apt: 
    name:
      # General utils
      - netcat
      - vim
      - rsync
      - openssl
      - wget
      - tcpdump
      - less
      - dnsutils
      - ethtool
      - python3-mysqldb
      - linux-firmware
      - whois
      - patch
      - chrony
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      # CloudStack specific utils
      - bridge-utils
      - sudo
      - vlan
      - ifenslave
      - openjdk-11-jre-headless
      - genisoimage
      - uuid-runtime
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - python3-libvirt
      - python3-pip
      - python3-setuptools
      - python3-netaddr
      - python3-passlib
    state: present
  become: yes

- name: Remove cloud-init packages
  apt: 
    name:
      - cloud-init
      - cloud-guest-utils 
      - eatmydata 
      - gdisk 
    state: absent 
    purge: yes
  become: yes