---
- name: Increase limits
  lineinfile: line="{{ item }}" dest="/etc/security/limits.conf"
  with_items:
    - "*               hard    nofile           65535"
    - "*               soft    nofile           65535"
    - "*               hard    nproc            65535"
    - "*               soft    nproc            65535"

- include_tasks: install_utils.yml
- include_tasks: sysstat.yml
- include_tasks: ntp.yml
- include_tasks: add_net_bridge.yml
