---
- name: Install chrony for time synchronization
  apt: 
    name: chrony
    state: present
    update_cache: yes

- name: Enable and start chrony
  service:
    name: chronyd
    state: started
    enabled: yes

- name: Configure chrony for better time sync
  lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^pool', line: 'pool pool.ntp.org iburst' }
    - { regexp: '^makestep', line: 'makestep 1.0 3' }

- name: Restart chrony
  service:
    name: chronyd
    state: restarted
