---
- name: Install sysstat
  apt: 
    name: sysstat
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Configure sysstat
  lineinfile:
    path: /etc/default/sysstat
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^ENABLED=', line: 'ENABLED="true"' }
    - { regexp: '^HISTORY=', line: 'HISTORY=7' }
    - { regexp: '^COMPRESSAFTER=', line: 'COMPRESSAFTER=10' }
    - { regexp: '^SADC_OPTIONS=', line: 'SADC_OPTIONS="-S DISK"' }

- name: Configure sysstat collection interval
  copy:
    dest: /etc/cron.d/sysstat
    content: |
      # Collect system activity data every 10 minutes
      */10 * * * * root /usr/lib/sysstat/sa1 1 1
      # Generate daily summary at 23:53
      53 23 * * * root /usr/lib/sysstat/sa2 -A

- name: Enable and start sysstat service
  service:
    name: sysstat
    state: started
    enabled: yes
